development:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@db:5432/lunches_development?sslmode=disable"}}

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@db:5432/lunches_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@db:5432/lunches_production?sslmode=disable"}}
